language: node_js

node_js:
  - node
  - lts/*
os:
  - linux
  - windows

install: yarn
cache: yarn

before_script:
  - git config --global user.email "travis@travis-ci.com"
  - git config --global user.name "Travis"

script:
  - yarn test
  - if [ $TRAVIS_OS_NAME = windows ]; then powershell kill -n gpg-agent; fi

jobs:
  include:
    - stage: coverage
      name: Coverage

      node_js: node
      os: linux

      before_script: skip

      script:
        - yarn test --coverage
        - yarn codecov

    - stage: deploy
      name: Deploy

      if: tag IS present

      node_js: node
      os: linux

      before_script: skip

      script:
        - yarn vsce package
        - echo $'## Changes\n\n' > release-notes.log
        - git log $(git log --tags --no-walk --pretty="format:%d" | sed 2q | sed "s/[()]//g; s ......  ; 1d")..@ --oneline --pretty=format:"%h %s" | awk '{print "- "$0}' >> release-notes.log

      deploy:
        - provider: releases
          token: $GITHUB_TOKEN
          file_glob: true
          file: "*.vsix"
          edge: true
          release_notes_file: release-notes.log
          on:
            branch: master
            tags: true
        - provider: script
          script: yarn vsce publish -p $VS_TOKEN
          edge: true
          on:
            branch: master
            tags: true
