language: node_js
node_js:
  - node
  - lts/*
install: yarn
cache: yarn
script:
  - yarn lint
  - yarn test --coverage
  - "if [ $TRAVIS_NODE_VERSION = node ]; then yarn cover; fi"
  - yarn vsce package
before_deploy:
  - echo $'## Changes\n\n' > release-notes.log
  - git log $(git tag | sort -r | sed -n "2p")..@ --oneline --pretty=format:"%h %s" | awk '{print "- "$0}' >> release-notes.log
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "*.vsix"
    edge: true
    release_notes_file: release-notes.log
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: $TRAVIS_NODE_VERSION = node
  - provider: script
    script: yarn vsce publish -p $VS_TOKEN
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: $TRAVIS_NODE_VERSION = node
