language: node_js
node_js:
  - "8"
  - "10"
  - "12"
install: yarn
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn vsce package
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: $TRAVIS_NODE_VERSION = 10
  - provider: script
    script: yarn vsce publish -p $VS_TOKEN
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: $TRAVIS_NODE_VERSION = 10
