name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ">=12"

      - name: Install Dependencies
        run: yarn install

      - name: Setup Environment
        run: |
          echo "::set-env name=RELEASE_TAG::${GITHUB_REF//refs\/tags\/}"
          echo "::set-env name=RAW_VERSION::${GITHUB_REF//refs\/tags\/v}"

      - name: Increment Version
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"

          yarn version --new-version $RAW_VERSION --no-git-tag-version

          git add package.json
          git commit -m "Increment version to $RELEASE_TAG"

      - name: Push Version
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: yarn vsce package

      - name: Publish
        run: yarn vsce publish -p ${{ secrets.VS_TOKEN }}

      - uses: AButler/upload-release-assets@v2.0
        with:
          files: syncify-*.vsix
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ env.RELEASE_TAG }}
